# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
    build:
        filters:  # using regex filters requires the entire branch to match
            branches:
                only:  # only branches matching the below regex filters will run
                    - master
        macos:
            xcode: "9.4.1"
        working_directory: ~/Users/jerry.shi/Desktop/circleCi/circleCiPOC
        environment:
            FL_OUTPUT_DIR: output
            FASTLANE_LANE: test
        shell: /bin/bash --login -o pipefail
        steps:
            - checkout
            - restore_cache:
                key: 1-gems-{{ checksum "Gemfile.lock" }}
            - run: bundle check
            - run: bundle install --path vendor/bundle
            - save_cache:
                key: 1-gems-{{ checksum "Gemfile.lock" }}
                paths:
                    - vendor/bundle
            - run:
                name: fastlane
                command: bundle exec fastlane custom_lane
            - run:
                name: fastlane build
                command: bundle exec fastlane scan
            - store_artifacts:
                path: output
            - store_test_results:
                path: output/scan